[build]
  command = "npm run build:sls"
  publish = "dist/angular-bfdx/browser"

# TO-DO: remove after cli redirect fix is out https://github.com/netlify/cli/pull/2920
# any additional redirects for the site should come *before* this one
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/angular-builder"
  status = 200

# TO-DO: remove when config-mutating bug is diagnosed by workflow
[functions]
included_files=["dist/angular-bfdx/browser/index.html"]
node_bundler="esbuild"

[[plugins]]
  package = "../"
